django_tutorial/community/urls.py
from django.urls import path
from .views import write, articlelist, viewdetail

app_name = 'community'
urlpatterns = [
 
    path('write/',write, name='write'),

    path('list/',articlelist, name='article_list'),

    path('view_detail/<int:num>/', viewdetail, name='view_detail'),
    
]

django_tutorial/dashboard/urls.py
from django.urls import path
from .views import dashboard

app_name = 'dashboard'
urlpatterns = [
 
    path('',dashboard, name='dashboard'),

]

django_tutorial/django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('write/',write, name='write'),
    # path('list/',articlelist, name='list'),
    #path('community/view_detail/<int:num>/',viewdetail, name='view_detail'),
    path('',include('single_page.urls')),
    path('community/', include('community.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    

]

django_tutorial/single_page/urls.py
from django.urls import path
from .views import index, aboutMe

app_name = 'single_page'
urlpatterns = [
    # / index
    path('',index, name='index'),
    # / aboutMe
    path('aboutme/',aboutMe, name='aboutMe'),
]

django_tutorial/community/models.py
from importlib.resources import contents
from django.db import models

# Create your models here.
class Article(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    contents = models.TextField()
    url = models.URLField()
    email = models.EmailField()
    cdate = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = "글 작성하기"

    def __str__(self):
        return f'{self.title}---{self.name}'

django_tutorial/dashboard/models.py
from tabnanny import verbose
from unicodedata import name
from django.db import models

# Create your models here.
class CountryData(models.Model):
    country = models.CharField(max_length=100)
    population = models.IntegerField()

    class Meta:
        verbose_name_plural = "각 나라별 인구"

    def __str__(self):
        return f'{self.country}---{self.population}'
        

django_tutorial/single_page/models.py
from django.db import models

# Create your models here.

django_tutorial/community/forms.py
from dataclasses import field, fields
from django.forms import ModelForm
from community.models import Article

class Form(ModelForm):
    class Meta:
        model = Article
        fields = ['name','title','contents','url','email']

django_tutorial/dashboard/forms.py
from dataclasses import field
from pyexpat import model
from django.forms import ModelForm
from .models import CountryData

class CountryDataForm(ModelForm):
    class Meta:
        model = CountryData
        # fields = ['country']  특정한 필드에서 사용할 때
        fields = '__all__'

django_tutorial/community/views.py
from django.shortcuts import get_object_or_404, redirect, render
from community.forms import Form
from .models import Article

# Create your views here.
def write(request):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            form.save()  #필드값 저장
            return redirect('/community/list/') #입력하고 나서, 정보가 남지않게됨. 정보를 넘기는것 

    else:
        form =Form()

    return render(request,'community/write.html', {'form': form })


#글 작성 목록
def articlelist(request):
    article_list=Article.objects.all()
    return render(request,'community/list.html',{'article_list': article_list})

def viewdetail(request, num=1):
    #article_detail = Article.objects.get(pk=num)
    article_detail = get_object_or_404(Article,pk=num)
    #pass #나중에 구현하려면 이렇게
    return render(request, 'community/view_detail.html',
    {'article_detail':article_detail})

django_tutorial/dashboard/views.py
from multiprocessing import reduction
from django.shortcuts import redirect, render
from .models import CountryData
from .forms import CountryDataForm
# Create your views here.
# 함수 안에는 request 
def dashboard(request):
    #각 나라와 인구숫자 가져오기
    data = CountryData.objects.all()
    # add 버튼 클릭 , 값 입력 요청 처리
    if request.method =='POST':
    # DB입력
        form = CountryDataForm(request.POST)
        #폼에 입력한 나라
        input_country = form.data.get('country', None)
        #폼에 입력한 인구수
        input_num = form.data.get('population', None)
        if form.is_valid():
            # DB 나라이름이 중복된 경우 업데이트
            # 아닌경우, 추가
            #CRUD : create , Read , Update , Delate
            CountryData.objects.update_or_create(
                #filter
                country = input_country,
                #new value
                defaults = {
                    'country': input_country,
                    'population': input_num
                }
            )

            #form.save()
            return redirect('.')
    #form 출력 
    else:
        #form 객체 생성
        form = CountryDataForm()
    

    #변수처리, db데이터 가져오기
    #데이터 필터링, form처리
    #aaa="대시보드 만들기"
    #form = CountryDataForm()
    context = {'dataset': data, 'form': form }
    return render(request, 
    'dashboard/dashboard.html', context)
    # return render(request, '랜더링할 템플릿파일',{템플릿에 전달할 데이터 키: 데이터 변수} )


    # class CountryData(models.Model):
    # country = models.CharField(max_length=100)
    # population = models.IntegerField()

django_tutorial/django_tutorial/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .froms import CreateUserForm

class UserCreateView(CreateView):
    form_class = CreateUserForm
    template_name = "registration/register.html"
    # 폼에 입력된 내용에 에러가 없고, 테이블 레코드 생성이 완료된후에
    # 이동할 URL을 지정.

    success_url = reverse_lazy("register_done")

class UserCreateDoneTV(TemplateView):
    template_name = "registration/register_done.html"

django_tutorial/single_page/views.py
from django.shortcuts import render
from community.models import Article

# Create your views here.
def index(request):
    lastest_article_list = Article.objects.all().order_by('-cdate')[:3]
    return render(request, 'single_page/index.html',{'lastest_article_list':lastest_article_list})
    #return render(request, '/index.html', {'latest_article_list': latest_article_list})

def aboutMe(request):
    # return rander(request,'템플릿파일',{'키':데이터_변수} )
    return render(request,'single_page/aboutme.html',)

django_tutorial/community/templates/community/list.html
{% extends "base.html" %}
{% block title %}메모 목록{% endblock %}

{% block part_style %}
    <style>
        .article_box{
            width: 500px;
            background-color: aqua;
        }
        p > span{
            padding: 10px 20px;
            text-align: center;
        }
        p > span:first-of-type{
            width: 150px;
            display: inline-block;
        }
        ul {
            border-top: 2px solid gray;
        }
        ul > li > span{
            margin: 5px;
        }
        ul > li > span:first-of-type{
            width: 150px;
            display: inline-block;
        }
    </style>
{% endblock %}
{% block content %}
</head>
<body>
    <div class="article_box">
    <p>
        <span> 제목 </span>
        <span> 이름 </span> 
        <span> 작성 날짜 </span>
    </p>
    <ul>
    {% for article in article_list %}
     <li> <a href="/community/view_detail/{{ article.id }}"><span>{{article.title}}</span> 
        <span>{{ article.name }}</span>
        <span> {{ article.cdate|date:"Y년 M d일 D"}}</span>
    </li>
     {% endfor %}
    </ul>
    </div>
{% endblock content%}

django_tutorial/community/templates/community/view_detail.html
{% extends "base.html" %}
{% block title %}{{article_detail.pk}}번글 세부내용{% endblock %}



{% block content %}
    <p>{{ article_detail. }}</p>
    <table>
        <tr>
            <th>no</th>
            <td>{{article_detail.pk}}</td>
        </tr>
    </table>
    <table>
        <tr>
            <th>제목</th>
            <td>{{article_detail.name}}</td>
        </tr>
    </table>    <table>
        <tr>
            <th>내용</th>
            <td>{{article_detail.content}}</td>
        </tr>
    </table>    <table>
        <tr>
            <th></th>
            <td>{{article_detail.url}}</td>
        </tr>
    </table>    <table>
        <tr>
            <th></th>
            <td>{{article_detail.email}}</td>
        </tr>
    </table>    <table>
        <tr>
            <th></th>
            <td>{{article_detail.cdate}}</td>
        </tr>
    </table>    <table>
        <tr>
            <th></th>
            <td>{{article_detail.title}}</td>
        </tr>
    </table>
   
{% endblock content %}

django_tutorial/community/templates/community/write.html
{% extends "base.html" %}
{% block title %}글 작성{% endblock %}

{% block content %}
        <h1>장고테스트</h1>
        <p>헬로 장고 </p>
        <p>{{ hello }}</p>
    <form action="" method="post">
        <table>
            {% csrf_token %} 
            {{form}}
        </table>
        <button type="submit">확인</button>
    </form>
{% endblock content %}

django_tutorial/dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% block title %}각 나라 인구 대시보드{% endblock %}


{% block content %}
    {% load crispy_forms_tags %}
    <!-- pt-1은 4px,  pt-3은 16px임, pt-4는 24px -->
    <div class="row mt-3 pt-3">
        <div class="col-md-4">
            <div class="border p-3 shadow">
            <h4>Add Data</h4>
                <form method="post">
                {%csrf_token%}
                {{ form | crispy }}
                <button type="submit"class='btn btn-success btn-block'>Add</button>
                </form>
            </div>
        </div>
        <div class="col-md-8">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>
{% endblock %}


{% block part_script %}
 <!-- chart.js cdn -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.0/dist/chart.min.js"></script>
<script>
const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        // labels: ['대한민국', '일본'],
        labels: [
                {% for data in dataset %}
                '{{ data.country }}',  
                {% endfor %}
            ],
        datasets: [{
            label: '각 나라별 인구수',
            // data: [50, 80],
            data: [
                {% for data in dataset %}
                '{{ data.population }}',  
                {% endfor %}

            ],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>
{% endblock part_script %}

django_tutorial/single_page/templates/single_page/aboutme.html
{% extends "base.html" %}
{% block part_script %}{% endblock %}
{% block title %}자기소개{% endblock %}

{% load static %}
{% block content %}

       
        {% block part_style%}
        <link rel="stylesheet" href="{% static 'css/aboutme.css' %}">
        {% endblock %}


        <figure>
            <video src="/imgs/visual.mp4" autoplay muted loop></video>
            <div class="inner">
                <h1>Portfolio</h1>
                <p>Casio Aims to Provide the Important Things You Keep Close in Life. <br>
                    Casio is creating new value by not only providing products, but also maintaining a dialogue with customers.</p>
                <a href="#">view detail</a>
            </div>
        </figure>
    
        <section>
            <div class="inner">
                <h1>Daily Watch</h1>
                <div class="wrap">
                    <article>
                        <div class="pic">
                            <img src="img/casio.JPG" alt="1번째 콘텐츠 이미지">
                        </div>
                        <h2><a href="#">News</a></h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae minus, eaque corrupti vero ad
                            maiores!</p>
                    </article>
    
                    <article>
                        <div class="pic">
                            <img src="img/watch2.jpg" alt="2번째 콘텐츠 이미지">
                        </div>
                        <h2><a href="#">Details</a></h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae minus, eaque corrupti vero ad
                            maiores!</p>
                    </article>
    
                    <article>
                        <div class="pic">
                            <img src="img/watch3.jpg" alt="3번째 콘텐츠 이미지">
                        </div>
                        <h2><a href="#">Best Casio.</a></h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae minus, eaque corrupti vero ad
                            maiores!</p>
                    </article>
    
                    <article>
                        <div class="pic">
                            <img src="img/watch4.jpg" alt="4번째 콘텐츠 이미지">
                        </div>
                        <h2><a href="#">Daily Casio.</a></h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae minus, eaque corrupti vero ad
                            maiores!</p>
                    </article>
                </div>
            </div>
        </section>
    

{% endblock content %}

django_tutorial/single_page/templates/single_page/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}장고 프로젝트 홈{% endblock title %}

{% block part_style %}
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
{% endblock part_style %}

{% block content %}
    <div class="article_box">
        <p>
        <span> 제목 </span>
        <span> 이름 </span> 
        <span> 작성 날짜 </span>
        </p>
            <ul>         
        {% for article in lastest_article_list %} 
         <li> <a href="community/view_detail/{{ article.id }}">
             <span>{{article.title}}</span> 
            <span>{{ article.name }}</span> 
            <span> {{ article.cdate|date:"Y년 M d일 D"}}</span>
        {% endfor %}
        </li>
        </ul>
        <p><a href="/community/list/">전체 목록보기</a></p>
        <button><a href="/community/write/">메모 작성하기</a></button>
    </div>
    

    <p class="main_img"><img src="{% static '/imgs/img01.gif' %}" alt="시계 이미지"></p>
    <p class="main_img"><img src="{% static '/imgs/img01.gif' %}" alt="시계 이미지"></p>
    
    {% comment "주석"  %}
    <!-- <p><img src="{% static'/imgs/img01.gif'%}" alt="시계 이미지"></p> -->
    <!-- <p><img src="{%static '/imgs/img_01.gif'%}" alt=""></p> -->
    {% endcomment  %}
   
{% endblock content %}

django_tutorial/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 부트스트랩 CDN -->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/82d01722e6.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <title>{% block title %}장고 첫 프로젝트{% endblock %} </title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    {% block part_style%}{% endblock %}
</head>
<body>
    {% include './partials/nav.html'  %}
    <section class="container">
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </section>
    {% include './partials/footer.html'  %}
</body>
</html>
<script src="{% static '/js/main.js' %}"></script>
{% block part_script %}{% endblock %}

django_tutorial/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .article_box{
            width: 500px;
            background-color: aqua;
        }
        p > span{
            padding: 10px 20px;
            text-align: center;
        }
        p > span:first-of-type{
            width: 150px;
            display: inline-block;
        }
        ul {
            border-top: 2px solid gray;
        }
        ul > li > span{
            margin: 5px;
        }
        ul > li > span:first-of-type{
            width: 150px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="article_box">
    <p>
        <span> 제목 </span>
        <span> 이름 </span> 
        <span> 작성 날짜 </span>
    </p>
    <ul>
    {% for article in article_list %}
     <li> <a href="/view_detail/{{ article.id }}"><span>{{article.title}}</span> 
        <span>{{ article.name }}</span>
        <span> {{ article.cdate|date:"Y년 M d일 D"}}</span>
    </li>
     {% endfor %}
    </ul>
    </div>
</body>
</html>

django_tutorial/templates/partials/footer.html
<footer class="py-5 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>

django_tutorial/templates/partials/nav.html
<div class="nav navbar-dark bg-primary">
<div class ="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic"><a class="nav-link text-white" href="{% url 'single_page:index' %}">COZLAB</a></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'single_page:aboutMe' %}">AboutMe</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'community:write' %}">Memo</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>

                <li class="nav-item dropdown mx-1 btn btn-primary">
                  <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" href="">Admin</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'community:article_list' %}">메모 리스트</a>
                      <a class="dropdown-item" href="#">변경 가능 리스트</a> 
                  </div>
              </li>
          </ul>
          <!-- 로그인 인증 -->
          <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                  <i class="fas fa-user-lock"></i>&ensp; &ensp;{% firstof user.get_short_name user.get_username %}</a>

                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> 
                  <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a> 
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                  <i class="fas fa-lock-open"></i>&ensp;Anonymous&ensp;</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'login' %} ">Login</a> 
                  <a class="dropdown-item" href="{% url 'register'%}">Register</a>
                </div>
                {% endif %}
              </li>
            </ul>
    
        </div>
    </nav>
  </div>
  </div>

django_tutorial/templates/partials/nav_bak.html
<style>
  .nav_bar{
    width: 80vw;
    margin: 0 auto;
  }
</style>
<div class="nav bg-light">
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">WatchMagazine<span class="sr-only"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/aboutme/">About Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/dashboard/">대시보드</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/community/write/">메모작성</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
              Dropdown 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/community/list/">메모리스트</a>
              <a class="dropdown-item" href="/community/write/">메모 작성</a>
              <a class="dropdown-item" href="/community/view_detail/1/">메모 디테일</a>
            </div>
          </li>
        </ul>
      </div> 
    </nav>
  </div> 
</div>